version: '3.3'

services:
  db:
    container_name: zian-postgres
    image: postgres
    volumes:
      - zian-pgdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=zian
      - POSTGRES_USER=zian
      - POSTGRES_PASSWORD=zian
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"

volumes:
  zoo-pgdb:
